"use client";

import { useState, useEffect, useCallback, useMemo } from "react";
import { useTranslations } from "next-intl";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { ArrowLeft, Trash2, CheckCircle } from "lucide-react";
import { cn } from "@/lib/utils";

import { useExciseMovement } from "../hooks";
import {
  createExciseMovement,
  updateExciseMovement,
  deleteExciseMovement,
  getExciseWarehouses,
} from "../actions";
import type {
  ExciseMovementType,
  ExciseDirection,
  CreateExciseMovementInput,
} from "../types";

// ── Direction mapping ──────────────────────────────────────────

const directionMap: Record<string, ExciseDirection> = {
  production: "in",
  release: "out",
  loss: "out",
  destruction: "out",
  transfer_in: "in",
  transfer_out: "out",
  adjustment: "out",
};

const MOVEMENT_TYPES: ExciseMovementType[] = [
  "production",
  "release",
  "loss",
  "destruction",
  "transfer_in",
  "transfer_out",
  "adjustment",
];

// ── Props ──────────────────────────────────────────────────────

interface ExciseMovementDetailProps {
  id: string;
}

// ── Component ──────────────────────────────────────────────────

export function ExciseMovementDetail({
  id,
}: ExciseMovementDetailProps): React.ReactNode {
  const t = useTranslations("excise");
  const router = useRouter();
  const isNew = id === "new";

  const {
    data: movement,
    isLoading,
    mutate,
  } = useExciseMovement(isNew ? null : id);

  // Warehouse options
  const [warehouseOptions, setWarehouseOptions] = useState<
    Array<{ id: string; name: string }>
  >([]);

  // Delete dialog
  const [deleteDialogOpen, setDeleteDialogOpen] = useState(false);

  // Form state
  const [date, setDate] = useState(
    new Date().toISOString().split("T")[0] ?? ""
  );
  const [movementType, setMovementType] =
    useState<ExciseMovementType>("adjustment");
  const [direction, setDirection] = useState<ExciseDirection>("in");
  const [volumeHl, setVolumeHl] = useState("");
  const [plato, setPlato] = useState("");
  const [warehouseId, setWarehouseId] = useState("");
  const [description, setDescription] = useState("");
  const [notes, setNotes] = useState("");

  // Determine if auto-generated (has stockIssueId)
  const isAutoGenerated = Boolean(movement?.stockIssueId);
  const isDraft = isNew || movement?.status === "draft";
  const isManual =
    isNew || (!isAutoGenerated && movement?.movementType === "adjustment");

  // Computed tax — taxRate is stored only on the taxable movement (per excise_tax_point)
  const computedTaxRate = movement?.taxRate
    ? Number(movement.taxRate)
    : 0;
  const computedTaxAmount = useMemo(() => {
    if (!plato || !volumeHl) return null;
    const vol = Number(volumeHl);
    const p = Number(plato);
    if (isNaN(vol) || isNaN(p) || computedTaxRate === 0) return null;
    return vol * p * computedTaxRate;
  }, [plato, volumeHl, computedTaxRate]);

  // Load warehouse options
  useEffect(() => {
    let cancelled = false;
    getExciseWarehouses()
      .then((opts) => {
        if (!cancelled) setWarehouseOptions(opts);
      })
      .catch((error: unknown) => {
        console.error("Failed to load warehouses:", error);
      });
    return (): void => {
      cancelled = true;
    };
  }, []);

  // Populate form from existing data
  useEffect(() => {
    if (movement) {
      setDate(movement.date);
      setMovementType(movement.movementType as ExciseMovementType);
      setDirection(movement.direction as ExciseDirection);
      setVolumeHl(movement.volumeHl);
      setPlato(movement.plato ?? "");
      setWarehouseId(movement.warehouseId ?? "");
      setDescription(movement.description ?? "");
      setNotes(movement.notes ?? "");
    }
  }, [movement]);

  // Auto-update direction when movementType changes (for new/manual)
  useEffect(() => {
    if (isNew || isManual) {
      const newDir = directionMap[movementType] ?? "in";
      setDirection(newDir);
    }
  }, [movementType, isNew, isManual]);

  // ── Handlers ─────────────────────────────────────────────────

  const handleSave = useCallback(async (): Promise<void> => {
    try {
      if (isNew) {
        const period = date.substring(0, 7);
        const input: CreateExciseMovementInput = {
          movementType,
          volumeHl,
          direction,
          date,
          period,
          warehouseId: warehouseId || undefined,
          plato: plato || undefined,
          description: description || undefined,
          notes: notes || undefined,
          status: "draft",
        };
        const created = await createExciseMovement(input);
        toast.success(t("movements.detail.save"));
        router.push(`/stock/excise/${created.id}`);
      } else {
        if (isAutoGenerated) {
          // Auto-generated: only plato and notes editable
          await updateExciseMovement(id, {
            plato: plato || null,
            notes: notes || null,
          });
        } else {
          // Manual: full editing
          await updateExciseMovement(id, {
            movementType,
            volumeHl,
            direction,
            date,
            warehouseId: warehouseId || null,
            description: description || null,
            notes: notes || null,
            plato: plato || null,
          });
        }
        toast.success(t("movements.detail.save"));
        mutate();
      }
    } catch (error) {
      console.error("Failed to save excise movement:", error);
      toast.error(String(error));
    }
  }, [
    isNew,
    id,
    movementType,
    volumeHl,
    direction,
    date,
    warehouseId,
    plato,
    description,
    notes,
    isAutoGenerated,
    router,
    t,
    mutate,
  ]);

  const handleConfirm = useCallback(async (): Promise<void> => {
    try {
      await updateExciseMovement(id, { status: "confirmed" });
      toast.success(t("movements.detail.confirm"));
      mutate();
    } catch (error) {
      console.error("Failed to confirm excise movement:", error);
      toast.error(String(error));
    }
  }, [id, t, mutate]);

  const handleDelete = useCallback(async (): Promise<void> => {
    try {
      await deleteExciseMovement(id);
      toast.success(t("movements.detail.delete"));
      router.push("/stock/excise");
    } catch (error) {
      console.error("Failed to delete excise movement:", error);
      toast.error(String(error));
    }
  }, [id, router, t]);

  // ── Status Badge ─────────────────────────────────────────────

  const statusBadge = useMemo(() => {
    const status = movement?.status ?? "draft";
    const variants: Record<string, string> = {
      draft: "bg-gray-100 text-gray-700",
      confirmed: "bg-green-100 text-green-700",
      reported: "bg-blue-100 text-blue-700",
    };
    return (
      <Badge variant="outline" className={variants[status] ?? ""}>
        {t(`movements.status.${status}` as Parameters<typeof t>[0])}
      </Badge>
    );
  }, [movement?.status, t]);

  const directionBadge = useMemo(() => {
    const className =
      direction === "in"
        ? "bg-green-100 text-green-700"
        : "bg-red-100 text-red-700";
    return (
      <Badge variant="outline" className={className}>
        {t(`movements.direction.${direction}` as Parameters<typeof t>[0])}
      </Badge>
    );
  }, [direction, t]);

  // ── Loading ──────────────────────────────────────────────────

  if (!isNew && isLoading) {
    return (
      <div className="flex flex-col gap-6 p-6">
        <div className="animate-pulse space-y-4">
          <div className="h-8 w-48 rounded bg-muted" />
          <div className="h-64 rounded bg-muted" />
        </div>
      </div>
    );
  }

  // ── Render ───────────────────────────────────────────────────

  const title = isNew
    ? t("movements.detail.newTitle")
    : t("movements.detail.title");

  return (
    <div className="flex flex-col gap-6 p-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button
          variant="ghost"
          size="icon"
          onClick={() => {
            router.push("/stock/excise");
          }}
        >
          <ArrowLeft className="size-4" />
        </Button>
        <h1 className="text-2xl font-bold tracking-tight">{title}</h1>
        {!isNew && (
          <div className="flex items-center gap-2">
            {statusBadge}
            {directionBadge}
          </div>
        )}

        {/* Action buttons — right side of header */}
        <div className="ml-auto flex items-center gap-2">
          {isDraft && (
            <>
              <Button onClick={() => void handleSave()}>
                {t("movements.detail.save")}
              </Button>
              {!isNew && (
                <Button
                  variant="default"
                  onClick={() => void handleConfirm()}
                >
                  <CheckCircle className="mr-1 size-4" />
                  {t("movements.detail.confirm")}
                </Button>
              )}
              {!isNew &&
                !isAutoGenerated &&
                movement?.movementType === "adjustment" && (
                  <Button
                    variant="destructive"
                    onClick={() => {
                      setDeleteDialogOpen(true);
                    }}
                  >
                    <Trash2 className="mr-1 size-4" />
                    {t("movements.detail.delete")}
                  </Button>
                )}
            </>
          )}
        </div>
      </div>

      {/* Auto-generated notice */}
      {isAutoGenerated && (
        <div className="rounded-md border border-blue-300 bg-blue-50 px-4 py-2 text-sm text-blue-800">
          {t("movements.detail.autoGenerated")}
          {movement?.stockIssueCode && (
            <span className="ml-1 font-medium">
              ({movement.stockIssueCode})
            </span>
          )}
        </div>
      )}

      <Card>
        <CardHeader>
          <CardTitle className="text-base">
            {t("movements.detail.fields.movementType")}
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            {/* Date */}
            <div className="space-y-2">
              <Label>{t("movements.detail.fields.date")}</Label>
              <Input
                type="date"
                value={date}
                onChange={(e) => {
                  setDate(e.target.value);
                }}
                disabled={!isDraft || isAutoGenerated}
              />
            </div>

            {/* Movement Type */}
            <div className="space-y-2">
              <Label>{t("movements.detail.fields.movementType")}</Label>
              {isAutoGenerated || !isDraft ? (
                <div className="flex h-9 items-center">
                  <Badge variant="outline">
                    {t(
                      `movements.movementType.${movementType}` as Parameters<
                        typeof t
                      >[0]
                    )}
                  </Badge>
                </div>
              ) : (
                <Select
                  value={movementType}
                  onValueChange={(val) => {
                    setMovementType(val as ExciseMovementType);
                  }}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {MOVEMENT_TYPES.map((mt) => (
                      <SelectItem key={mt} value={mt}>
                        {t(
                          `movements.movementType.${mt}` as Parameters<
                            typeof t
                          >[0]
                        )}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            </div>

            {/* Direction — editable for adjustment, readonly for others */}
            <div className="space-y-2">
              <Label>{t("movements.detail.fields.direction")}</Label>
              {movementType === "adjustment" && isDraft ? (
                <Select
                  value={direction}
                  onValueChange={(v) => {
                    setDirection(v as ExciseDirection);
                  }}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="in">
                      {t("movements.direction.in" as Parameters<typeof t>[0])}
                    </SelectItem>
                    <SelectItem value="out">
                      {t("movements.direction.out" as Parameters<typeof t>[0])}
                    </SelectItem>
                  </SelectContent>
                </Select>
              ) : (
                <div className="flex h-9 items-center">{directionBadge}</div>
              )}
            </div>

            {/* Volume */}
            <div className="space-y-2">
              <Label>{t("movements.detail.fields.volumeHl")}</Label>
              <Input
                type="number"
                step="0.01"
                value={volumeHl}
                onChange={(e) => {
                  setVolumeHl(e.target.value);
                }}
                disabled={!isDraft || isAutoGenerated}
              />
            </div>

            {/* Plato */}
            <div className="space-y-2">
              <Label>{t("movements.detail.fields.plato")}</Label>
              <Input
                type="number"
                step="0.1"
                value={plato}
                onChange={(e) => {
                  setPlato(e.target.value);
                }}
                disabled={!isDraft}
              />
              {movement?.platoSource && (
                <p className="text-xs text-muted-foreground">
                  {t(
                    `movements.detail.platoSource.${movement.platoSource}` as Parameters<
                      typeof t
                    >[0]
                  )}
                </p>
              )}
            </div>

            {/* Tax Rate (readonly) */}
            <div className="space-y-2">
              <Label>{t("movements.detail.fields.taxRate")}</Label>
              <div className="flex h-9 items-center text-sm text-muted-foreground">
                {movement?.taxRate
                  ? `${Number(movement.taxRate).toLocaleString("cs-CZ")} Kc/°P/hl`
                  : "---"}
              </div>
            </div>

            {/* Tax Amount (readonly computed) */}
            <div className="space-y-2">
              <Label>{t("movements.detail.fields.taxAmount")}</Label>
              <div
                className={cn(
                  "flex h-9 items-center text-sm font-medium",
                  computedTaxAmount !== null && computedTaxAmount > 0
                    ? "text-red-600"
                    : "text-muted-foreground"
                )}
              >
                {computedTaxAmount !== null
                  ? `${computedTaxAmount.toLocaleString("cs-CZ", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} Kc`
                  : movement?.taxAmount
                    ? `${Number(movement.taxAmount).toLocaleString("cs-CZ", { minimumFractionDigits: 2, maximumFractionDigits: 2 })} Kc`
                    : "---"}
              </div>
            </div>

            {/* Warehouse */}
            <div className="space-y-2">
              <Label>{t("movements.detail.fields.warehouseId")}</Label>
              {!isDraft || isAutoGenerated ? (
                <div className="flex h-9 items-center text-sm">
                  {movement?.warehouseName ?? "---"}
                </div>
              ) : (
                <Select
                  value={warehouseId}
                  onValueChange={setWarehouseId}
                >
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    {warehouseOptions.map((wh) => (
                      <SelectItem key={wh.id} value={wh.id}>
                        {wh.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              )}
            </div>

            {/* Batch (readonly) */}
            {movement?.batchNumber && (
              <div className="space-y-2">
                <Label>{t("movements.detail.fields.batchId")}</Label>
                <div className="flex h-9 items-center text-sm">
                  {movement.batchNumber}
                </div>
              </div>
            )}

            {/* Stock Issue (readonly) */}
            {movement?.stockIssueCode && (
              <div className="space-y-2">
                <Label>{t("movements.detail.fields.stockIssueId")}</Label>
                <div className="flex h-9 items-center text-sm">
                  {movement.stockIssueCode}
                </div>
              </div>
            )}

            {/* Description */}
            <div className="space-y-2">
              <Label>{t("movements.detail.fields.description")}</Label>
              <Input
                value={description}
                onChange={(e) => {
                  setDescription(e.target.value);
                }}
                disabled={!isDraft || isAutoGenerated}
              />
            </div>

            {/* Notes */}
            <div className="space-y-2 sm:col-span-2">
              <Label>{t("movements.detail.fields.notes")}</Label>
              <Textarea
                value={notes}
                onChange={(e) => {
                  setNotes(e.target.value);
                }}
                disabled={!isDraft}
                rows={3}
              />
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Delete confirmation dialog */}
      <AlertDialog open={deleteDialogOpen} onOpenChange={setDeleteDialogOpen}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>
              {t("movements.detail.delete")}
            </AlertDialogTitle>
            <AlertDialogDescription>
              {t("movements.detail.delete")}
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t("movements.detail.back")}</AlertDialogCancel>
            <AlertDialogAction onClick={() => void handleDelete()}>
              {t("movements.detail.delete")}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  );
}
